# Generated by Django 6.0.6 on 2026-06-28 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_masked', models.CharField(max_length=100)),
                ('strength_label', models.CharField(max_length=20)),
                ('strength_score', models.IntegerField()),
                ('entropy', models.FloatField(default=0)),
                ('was_breached', models.BooleanField(default=False)),
                ('breach_count', models.IntegerField(default=0)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
